Program(["test.cpp",
         "node.cpp",
         "const_node.cpp",
         "binary_nodes.cpp",
         "unary_nodes.cpp",
         "var_node.cpp",
         "scanner.cpp",
         "functions.cpp",
         "multiple_nodes.cpp"],
        CCFLAGS="/EHsc /O2",
        MSVC_VERSION=15.0)